from __future__ import annotations

import json
import sqlite3
from pathlib import Path
from typing import Any

from .config import AppConfig
from .db import MySQLDatabase, chunks


def _open(path: Path) -> sqlite3.Connection:
    conn = sqlite3.connect(path)
    conn.row_factory = sqlite3.Row
    return conn


def _rows(conn: sqlite3.Connection, sql: str, params: tuple[Any, ...] = ()) -> list[dict[str, Any]]:
    return [dict(r) for r in conn.execute(sql, params).fetchall()]


def audit_results(results: str | Path, cfg: AppConfig | None = None, sample_limit: int = 20) -> dict[str, Any]:
    path = Path(results)
    if path.is_dir():
        path = path / "comparison_results.sqlite"
    if not path.exists():
        raise FileNotFoundError(path)

    with _open(path) as conn:
        tables = {r[0] for r in conn.execute("SELECT name FROM sqlite_master WHERE type='table'")}
        if not {"anomalies", "current_items", "current_hosts"}.issubset(tables):
            raise RuntimeError("Arquivo não contém as tabelas necessárias para auditoria.")

        missing_total = conn.execute("SELECT COUNT(*) FROM anomalies WHERE category='ITEM_MISSING'").fetchone()[0]
        missing_but_loaded = conn.execute("""
            SELECT COUNT(*) FROM anomalies a
            JOIN current_items c ON c.itemid=a.itemid
            WHERE a.category='ITEM_MISSING'
        """).fetchone()[0]
        disabled_host_anomalies = conn.execute("""
            SELECT COUNT(*) FROM anomalies a
            JOIN current_hosts h ON h.hostid=a.hostid
            WHERE COALESCE(h.host_status,0)<>0
        """).fetchone()[0]
        interface_fallback = conn.execute("""
            SELECT COUNT(*) FROM anomalies a
            JOIN current_items c ON c.itemid=a.itemid
            WHERE TRIM(COALESCE(a.current_error,''))<>''
              AND a.current_error=COALESCE(c.interface_error,'')
              AND COALESCE(c.rt_error,'')<>COALESCE(c.interface_error,'')
        """).fetchone()[0]
        error_not_equal_rtdata = conn.execute("""
            SELECT COUNT(*) FROM anomalies a
            JOIN current_items c ON c.itemid=a.itemid
            WHERE COALESCE(a.current_error,'')<>COALESCE(c.rt_error,'')
        """).fetchone()[0]

        result: dict[str, Any] = {
            "results": str(path),
            "item_missing_total": missing_total,
            "item_missing_but_present_in_stored_current_items": missing_but_loaded,
            "anomalies_on_current_disabled_hosts": disabled_host_anomalies,
            "item_error_probably_fell_back_to_interface_error": interface_fallback,
            "stored_current_error_differs_from_item_rtdata_error": error_not_equal_rtdata,
            "samples": {
                "missing_but_loaded": _rows(conn, """
                    SELECT a.itemid,a.host,a.item_name,a.key_,c.host current_host,c.name current_name,c.key_ current_key
                    FROM anomalies a JOIN current_items c ON c.itemid=a.itemid
                    WHERE a.category='ITEM_MISSING' LIMIT ?
                """, (sample_limit,)),
                "interface_fallback": _rows(conn, """
                    SELECT a.itemid,a.host,a.item_name,a.key_,a.current_error,c.rt_error,c.interface_error,c.item_type
                    FROM anomalies a JOIN current_items c ON c.itemid=a.itemid
                    WHERE TRIM(COALESCE(a.current_error,''))<>''
                      AND a.current_error=COALESCE(c.interface_error,'')
                      AND COALESCE(c.rt_error,'')<>COALESCE(c.interface_error,'')
                    LIMIT ?
                """, (sample_limit,)),
                "disabled_hosts": _rows(conn, """
                    SELECT a.hostid,a.host,a.host_name,COUNT(*) anomalies,h.host_status
                    FROM anomalies a JOIN current_hosts h ON h.hostid=a.hostid
                    WHERE COALESCE(h.host_status,0)<>0
                    GROUP BY a.hostid,a.host,a.host_name,h.host_status
                    ORDER BY anomalies DESC LIMIT ?
                """, (sample_limit,)),
            },
        }

        missing_ids = [int(r[0]) for r in conn.execute("SELECT itemid FROM anomalies WHERE category='ITEM_MISSING' ORDER BY itemid")]

    # Optional direct verification against the current Zabbix DB. This is the
    # strongest way to prove a false ITEM_MISSING in results generated by old versions.
    if cfg is not None and cfg.current is not None and missing_ids:
        live_found: dict[int, dict[str, Any]] = {}
        with MySQLDatabase(cfg.current) as db:
            for batch in chunks(missing_ids, cfg.report.batch_size):
                live_found.update(db.fetch_item_presence(batch))
        result["live_current_db_checked"] = True
        result["item_missing_but_present_live_in_items"] = len(live_found)
        result["samples"]["missing_but_present_live"] = list(live_found.values())[:sample_limit]
    else:
        result["live_current_db_checked"] = False

    return result


def write_audit(results: str | Path, output: str | Path | None = None) -> Path:
    data = audit_results(results)
    path = Path(results)
    if path.is_dir():
        base = path
    else:
        base = path.parent
    out = Path(output) if output else base / "integrity_audit.json"
    out.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    return out
