const state={
  view:'overview',filters:null,pageSize:50,
  pages:{items:1,lld:1,'lld-rules':1,roots:1,hosts:1,templates:1,'interface-hosts':1},
  sorts:{
    items:{key:'severity',dir:'desc'},lld:{key:'severity',dir:'desc'},'lld-rules':{key:'severity',dir:'desc'},
    roots:{key:'dependent_affected_count',dir:'desc'},hosts:{key:'anomaly_count',dir:'desc'},templates:{key:'rank',dir:'asc'},'interface-hosts':{key:'host_name',dir:'asc'}
  },
  columnFilters:{items:{},lld:{},'lld-rules':{},roots:{},hosts:{},templates:{},'interface-hosts':{}}
};
const titles={overview:['Visão geral','Validação pós-upgrade com o Zabbix 6 como baseline.'],recommendations:['Ajustes recomendados','Prioridades calculadas a partir das regressões encontradas.'],items:['Itens com regressão','Hosts desabilitados no Zabbix 7 são ignorados. Erro do item e erro da interface são exibidos separadamente.'],lld:['Discoveries / LLD','Perdas de filhos e perda operacional dos objetos do baseline.'],'lld-rules':['Regras LLD','Regras de discovery que estavam saudáveis e regrediram.'],roots:['Causas raiz','Master items que concentram regressões em itens dependentes.'],templates:['Templates base','Priorize correções pela origem dos itens herdados.'],hosts:['Hosts impactados','Concentração de regressões por host.'],'interface-hosts':['Hosts com falha de interface','Hosts habilitados em que todas as interfaces estão com erro ou indisponíveis; seus objetos são excluídos das regressões.']};
const fmt=n=>new Intl.NumberFormat('pt-BR').format(Number(n||0));
const pct=n=>`${Number(n||0).toLocaleString('pt-BR',{maximumFractionDigits:1})}%`;
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||r.statusText);return r.json()}
function toast(msg){const e=document.querySelector('#toast');e.textContent=msg;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2500)}
function sev(s){return `<span class="sev ${esc(s)}">${esc(s)}</span>`}
function tpl(v,r){return esc(v||(r.direct_template_name?`(base não resolvido · direto: ${r.direct_template_name})`:'(local/sem template)'))}
function interfaceType(v){return ({1:'Agent',2:'SNMP',3:'IPMI',4:'JMX'}[Number(v)]||`Tipo ${v??'-'}`)}
function interfaceAvailable(v){return ({0:'Desconhecida',1:'Disponível',2:'Indisponível'}[Number(v)]||String(v??''))}
function showView(view){state.view=view;document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${view}`));document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===view));document.querySelector('#pageTitle').textContent=titles[view][0];document.querySelector('#pageSubtitle').textContent=titles[view][1];loadView(view)}
document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelector('#refreshBtn').onclick=()=>loadView(state.view,true);

function barChart(id,rows,{critical=false}={}){const el=document.querySelector(id);if(!rows?.length){el.innerHTML='<div class="empty">Sem dados</div>';return}const max=Math.max(...rows.map(r=>Number(r.value||0)),1);el.innerHTML=rows.map(r=>`<div class="bar-row"><div class="bar-label" title="${esc(r.label)}">${esc(r.label)}</div><div class="bar-track"><div class="bar-fill ${critical&&Number(r.critical)>0?'critical':''}" style="width:${Math.max(1,Number(r.value)*100/max)}%"></div></div><div class="bar-value">${fmt(r.value)}</div></div>`).join('')}

async function loadOverview(){const [o,c]=await Promise.all([api('/api/overview'),api('/api/charts')]);document.querySelector('#dbVersion').textContent=`Zabbix ${esc(o.current_dbversion||'7')}`;const s=o.status,ms=document.querySelector('#migrationStatus');ms.className=`migration-status ${s.level}`;ms.innerHTML=`<div class="status-dot"></div><div><strong>${esc(s.label)}</strong><span>${esc(s.detail)}</span></div>`;const sm=o.summary||{};const cards=[['Itens baseline',sm.baseline_healthy_items_analyzed,'saudáveis no baseline'],['Regressões',sm.item_regressions,'itens'],['Templates impactados',o.templates_impacted,'templates base'],['Hosts impactados',sm.hosts_impacted,'hosts'],['LLD com perda',sm.lld_groups_with_loss,'grupos'],['Perda total LLD',sm.lld_total_loss,'grupos'],['Hosts 7 desabilitados',o.ignored_disabled_hosts,'ignorados'],['Hosts c/ interfaces em erro',o.interface_failure_hosts,'isolados do report']];document.querySelector('#cards').innerHTML=cards.map(x=>`<div class="card"><div class="label">${esc(x[0])}</div><div class="value">${fmt(x[1])}</div><div class="hint">${esc(x[2])}</div></div>`).join('');barChart('#templateChart',c.templates,{critical:true});barChart('#categoryChart',c.categories);barChart('#hostChart',c.hosts,{critical:true});barChart('#lldChart',c.lld);barChart('#lldReasonChart',c.lld_reasons);document.querySelector('#errorList').innerHTML=c.errors.length?c.errors.map(e=>`<div class="error-row"><div class="error-count">${fmt(e.value)}</div><div class="error-text">${esc(e.label)}</div></div>`).join(''):'<div class="empty">Sem mensagens de erro do item.</div>'}

async function loadRecommendations(){const d=await api('/api/recommendations');document.querySelector('#recBadge').textContent=d.count||'';document.querySelector('#recommendationsList').innerHTML=d.rows.length?d.rows.map(r=>`<article class="rec ${r.priority}"><div class="rec-head"><div class="rec-title"><span class="priority">${esc(r.priority)}</span><h3>${esc(r.title)}</h3></div><div class="rec-count">${fmt(r.count)}</div></div><p>${esc(r.why)}</p><div class="rec-action"><strong>Ação sugerida:</strong> ${esc(r.action)}</div>${r.evidence?.length?`<details><summary>Ver evidências (${r.evidence.length})</summary><div class="evidence">${r.evidence.map(e=>`<code>${esc(JSON.stringify(e,null,2))}</code>`).join('')}</div></details>`:''}</article>`).join(''):'<div class="empty">Nenhum ajuste recomendado.</div>'}

function makeFilters(id,categories,withSeverity=true){const root=document.querySelector(id);const templateOptions=(state.filters?.templates||[]).map(x=>`<option value="${esc(x.template_hostid)}">#${fmt(x.rank)} · ${esc(x.template_name||x.template_host)}</option>`).join('');root.innerHTML=`<input data-f="q" placeholder="Busca geral"><select data-f="template"><option value="">Todos templates base</option>${templateOptions}</select><select data-f="severity"><option value="">Todas severidades</option>${withSeverity?['CRITICAL','HIGH','WARNING'].map(x=>`<option>${x}</option>`).join(''):''}</select><select data-f="category"><option value="">Todas categorias</option>${categories.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}</select>`;root.querySelectorAll('input,select').forEach(el=>{let t;el.oninput=()=>{clearTimeout(t);t=setTimeout(()=>{state.pages[state.view]=1;loadView(state.view)},220)}})}
function qsFor(view,filterRootId=null){const p=new URLSearchParams({page:state.pages[view]||1,page_size:state.pageSize,sort:state.sorts[view]?.key||'',dir:state.sorts[view]?.dir||'desc'});const root=filterRootId?document.querySelector(filterRootId):null;root?.querySelectorAll('[data-f]').forEach(x=>{if(x.value)p.set(x.dataset.f,x.value)});Object.entries(state.columnFilters[view]||{}).forEach(([k,v])=>{if(v)p.set(`f_${k}`,v)});return p}
function col(label,key,render=null,cls='',sortable=true,filter=true){return {label,key,render,cls,sortable,filter}}
function renderTable(id,view,cols,rows){const t=document.querySelector(id);const sort=state.sorts[view]||{};const filters=state.columnFilters[view]||{};const head=cols.map(c=>`<th>${c.sortable?`<button class="sort-head" data-sort="${esc(c.key)}">${esc(c.label)} <span>${sort.key===c.key?(sort.dir==='asc'?'▲':'▼'):'↕'}</span></button>`:esc(c.label)}</th>`).join('');const filterRow=cols.map(c=>`<th>${c.filter?`<input class="col-filter" data-col="${esc(c.key)}" value="${esc(filters[c.key]||'')}" placeholder="Filtrar">`:''}</th>`).join('');t.innerHTML=`<thead><tr>${head}</tr><tr class="column-filters">${filterRow}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${cols.map(c=>`<td class="${c.cls||''}">${c.render?c.render(r[c.key],r):esc(r[c.key])}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${cols.length}" class="empty">Nenhum registro encontrado</td></tr>`}</tbody>`;t.querySelectorAll('.sort-head').forEach(b=>b.onclick=()=>{const k=b.dataset.sort;const cur=state.sorts[view];state.sorts[view]={key:k,dir:cur?.key===k&&cur.dir==='desc'?'asc':'desc'};state.pages[view]=1;loadView(view)});t.querySelectorAll('.col-filter').forEach(inp=>{let timer;inp.oninput=()=>{clearTimeout(timer);state.columnFilters[view][inp.dataset.col]=inp.value;timer=setTimeout(()=>{state.pages[view]=1;loadView(view)},280)}})}
function pager(id,view,d){document.querySelector(id).innerHTML=`<button ${d.page<=1?'disabled':''} data-p="prev">Anterior</button><span>Página ${fmt(d.page)} de ${fmt(d.pages)} · ${fmt(d.total)} registros</span><button ${d.page>=d.pages?'disabled':''} data-p="next">Próxima</button>`;document.querySelectorAll(`${id} button`).forEach(b=>b.onclick=()=>{state.pages[view]+=b.dataset.p==='next'?1:-1;loadView(view)})}

async function loadItems(){if(!state.filters)state.filters=await api('/api/filters');if(!document.querySelector('#itemFilters').children.length)makeFilters('#itemFilters',state.filters.item_categories);const d=await api('/api/items?'+qsFor('items','#itemFilters'));document.querySelector('#itemsMeta').textContent=`${fmt(d.total)} regressões`;renderTable('#itemsTable','items',[
  col('Sev.','severity',v=>sev(v)),col('Template base','base_template_name',(v,r)=>tpl(v,r)),col('Host','host_name',(v,r)=>esc(v||r.host)),col('Item ID','itemid'),
  col('Item no 6','item_name'),col('Key no 6','key_',null,'category'),col('Tipo 6','baseline_item_type'),col('Tipo 7','current_item_type'),col('Key no 7','current_key_',null,'category'),
  col('Categoria','category',v=>`<span class="category">${esc(v)}</span>`),col('Erro do item','current_error',v=>esc(v||''),'err'),col('Erro interface','current_interface_error',v=>esc(v||''),'err',false,true),
  col('Master','master_itemid'),col('Dependentes','dependent_affected_count',v=>fmt(v),'num'),col('Campos alterados','changed_fields')
],d.rows);pager('#itemsPager','items',d)}

async function loadLLD(){if(!state.filters)state.filters=await api('/api/filters');if(!document.querySelector('#lldFilters').children.length)makeFilters('#lldFilters',state.filters.lld_categories);const d=await api('/api/lld?'+qsFor('lld','#lldFilters'));document.querySelector('#lldMeta').textContent=`${fmt(d.total)} grupos LLD`;renderTable('#lldTable','lld',[col('Sev.','severity',v=>sev(v)),col('Template base','base_template_name',(v,r)=>tpl(v,r)),col('Host','host_name',(v,r)=>esc(v||r.host)),col('Rule ID','ruleid'),col('Discovery','rule_name'),col('Baseline','baseline_count',v=>fmt(v),'num'),col('Atual','current_present_count',v=>fmt(v),'num'),col('Perdidos','lost_count',v=>fmt(v),'num'),col('Perda','loss_pct',v=>pct(v),'num'),col('Perda operacional','operational_loss_pct',v=>pct(v),'num'),col('Not discovered','not_discovered_count',v=>fmt(v),'num'),col('Pending delete','pending_delete_count',v=>fmt(v),'num'),col('Desabilitados','disabled_count',v=>fmt(v),'num'),col('Categoria','category',v=>`<span class="category">${esc(v)}</span>`)],d.rows);pager('#lldPager','lld',d)}

async function loadLLDRules(){if(!state.filters)state.filters=await api('/api/filters');if(!document.querySelector('#lldRuleFilters').children.length)makeFilters('#lldRuleFilters',state.filters.lld_rule_categories);const d=await api('/api/lld-rules?'+qsFor('lld-rules','#lldRuleFilters'));document.querySelector('#lldRuleMeta').textContent=`${fmt(d.total)} regras LLD com regressão`;renderTable('#lldRuleTable','lld-rules',[col('Sev.','severity',v=>sev(v)),col('Template base','base_template_name',(v,r)=>tpl(v,r)),col('Host','host_name',(v,r)=>esc(v||r.host)),col('Rule ID','itemid'),col('Regra','rule_name'),col('Key','key_',null,'category'),col('Categoria','category',v=>`<span class="category">${esc(v)}</span>`),col('Erro do item','current_error',v=>esc(v||''),'err'),col('Campos alterados','changed_fields')],d.rows);pager('#lldRulePager','lld-rules',d)}

async function loadRoots(){const d=await api('/api/roots?'+qsFor('roots'));document.querySelector('#rootsMeta').textContent=`${fmt(d.total)} master items identificados`;renderTable('#rootsTable','roots',[col('Sev.','severity',v=>sev(v)),col('Template base','base_template_name',(v,r)=>tpl(v,r)),col('Host','host_name',(v,r)=>esc(v||r.host)),col('Item ID','itemid'),col('Master item','item_name'),col('Categoria','category',v=>`<span class="category">${esc(v)}</span>`),col('Dependentes afetados','dependent_affected_count',v=>`<strong>${fmt(v)}</strong>`,'num'),col('Erro do item','current_error',v=>esc(v||''),'err'),col('Campos alterados','changed_fields')],d.rows);if(document.querySelector('#rootsPager'))pager('#rootsPager','roots',d)}

async function loadTemplates(){const root=document.querySelector('#templateFilters');if(!root.children.length){root.innerHTML='<input data-f="q" placeholder="Buscar template base">';root.querySelector('input').oninput=()=>{state.pages.templates=1;setTimeout(()=>loadTemplates(),180)}}const d=await api('/api/templates?'+qsFor('templates','#templateFilters'));document.querySelector('#templatesMeta').textContent=`${fmt(d.total)} templates base impactados`;renderTable('#templatesTable','templates',[col('#','rank',v=>`<strong>${fmt(v)}</strong>`,'num'),col('Template base','template_name',(v,r)=>`<strong>${esc(v||r.template_host)}</strong><div class="muted">${esc(r.template_host||'')}</div>`),col('Impacto','impact_count',v=>`<strong>${fmt(v)}</strong>`,'num'),col('Hosts','hosts_affected',v=>fmt(v),'num'),col('Itens','item_regressions',v=>fmt(v),'num'),col('Critical','critical_count',v=>fmt(v),'num'),col('High','high_count',v=>fmt(v),'num'),col('Regras LLD','lld_rule_regressions',v=>fmt(v),'num'),col('LLDs c/ perda','lld_groups_with_loss',v=>fmt(v),'num'),col('Perda total','lld_total_loss',v=>fmt(v),'num'),col('Filhos perdidos','lld_lost_children',v=>fmt(v),'num'),col('Pending delete','lld_pending_delete',v=>fmt(v),'num'),col('Dependentes','dependent_affected',v=>fmt(v),'num'),col('Focar','template_hostid',(v,r)=>`<button class="focus-template" data-template="${esc(v)}" data-name="${esc(r.template_name)}">Ver itens</button>`,'',false,false)],d.rows);document.querySelectorAll('.focus-template').forEach(b=>b.onclick=()=>focusTemplate(b.dataset.template,b.dataset.name));pager('#templatesPager','templates',d)}
function focusTemplate(id,name){showView('items');setTimeout(()=>{const sel=document.querySelector('#itemFilters [data-f="template"]');if(sel){sel.value=id;state.pages.items=1;loadItems();toast(`Filtro aplicado: ${name}`)}},80)}

async function loadHosts(){const root=document.querySelector('#hostFilters');if(!root.children.length){root.innerHTML='<input data-f="q" placeholder="Buscar host">';root.querySelector('input').oninput=()=>{state.pages.hosts=1;setTimeout(()=>loadHosts(),180)}}const d=await api('/api/hosts?'+qsFor('hosts','#hostFilters'));document.querySelector('#hostsMeta').textContent=`${fmt(d.total)} hosts impactados`;renderTable('#hostsTable','hosts',[col('Host','host_name'),col('Total','anomaly_count',v=>`<strong>${fmt(v)}</strong>`,'num'),col('Critical','critical_count',v=>fmt(v),'num'),col('High','high_count',v=>fmt(v),'num'),col('Warning','warning_count',v=>fmt(v),'num'),col('Categorias','category_count',v=>fmt(v),'num'),col('Dependentes afetados','dependent_affected_count',v=>fmt(v),'num')],d.rows);pager('#hostsPager','hosts',d)}

async function loadInterfaceHosts(){const root=document.querySelector('#interfaceHostFilters');if(!root.children.length){root.innerHTML='<input data-f="q" placeholder="Buscar host, interface, endpoint ou erro">';root.querySelector('input').oninput=()=>{state.pages['interface-hosts']=1;setTimeout(()=>loadInterfaceHosts(),180)}}const d=await api('/api/interface-hosts?'+qsFor('interface-hosts','#interfaceHostFilters'));document.querySelector('#interfaceHostsMeta').textContent=`${fmt(d.host_total)} hosts isolados · ${fmt(d.total)} interfaces com erro`;renderTable('#interfaceHostsTable','interface-hosts',[col('Host','host_name'),col('Host ID','hostid'),col('Interface ID','interfaceid'),col('Tipo','interface_type',v=>esc(interfaceType(v))),col('Principal','interface_main',v=>Number(v)===1?'Sim':'Não'),col('Endpoint','endpoint',v=>`<code>${esc(v)}</code>`),col('Disponibilidade','interface_available',v=>esc(interfaceAvailable(v))),col('Erro da interface','interface_error',v=>esc(v||'Interface indisponível'),'err'),col('Proxy','proxy_ref'),col('Interfaces do host','interface_count',v=>fmt(v),'num')],d.rows);pager('#interfaceHostsPager','interface-hosts',d)}

async function loadView(view,refresh=false){try{if(refresh)state.filters=null;await ({overview:loadOverview,recommendations:loadRecommendations,items:loadItems,lld:loadLLD,'lld-rules':loadLLDRules,roots:loadRoots,templates:loadTemplates,hosts:loadHosts,'interface-hosts':loadInterfaceHosts}[view])();if(view!=='recommendations')loadRecommendations().catch(()=>{});if(refresh)toast('Dados atualizados')}catch(e){toast(e.message)}}
loadOverview().catch(e=>toast(e.message));loadRecommendations().catch(()=>{});
