const state={view:'overview',filters:null,pages:{items:1,lld:1,'lld-rules':1,hosts:1,templates:1},pageSize:50};
const titles={overview:['Visão geral','Validação pós-upgrade com o Zabbix 6 como baseline.'],recommendations:['Ajustes recomendados','Prioridades calculadas a partir das regressões encontradas.'],items:['Itens com regressão','Somente itens que estavam saudáveis no Zabbix 6.'],lld:['Discoveries / LLD','Perdas de filhos e perda operacional dos objetos do baseline.'],'lld-rules':['Regras LLD','Regras de discovery que estavam saudáveis e regrediram.'],roots:['Causas raiz','Master items que concentram regressões em itens dependentes.'],templates:['Templates base','Priorize correções pela origem dos itens herdados.'],hosts:['Hosts impactados','Concentração de regressões por host.']};
const fmt=n=>new Intl.NumberFormat('pt-BR').format(Number(n||0));
const pct=n=>`${Number(n||0).toLocaleString('pt-BR',{maximumFractionDigits:1})}%`;
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||r.statusText);return r.json()}
function toast(msg){const e=document.querySelector('#toast');e.textContent=msg;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function sev(s){return `<span class="sev ${esc(s)}">${esc(s)}</span>`}
function tpl(v,r){return esc(v||(r.direct_template_name?`(base não resolvido · direto: ${r.direct_template_name})`:'(local/sem template)'))}
function showView(view){state.view=view;document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${view}`));document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===view));document.querySelector('#pageTitle').textContent=titles[view][0];document.querySelector('#pageSubtitle').textContent=titles[view][1];loadView(view)}

document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelector('#refreshBtn').onclick=()=>loadView(state.view,true);

function barChart(id,rows,{critical=false}={}){const el=document.querySelector(id);if(!rows?.length){el.innerHTML='<div class="empty">Sem dados</div>';return}const max=Math.max(...rows.map(r=>Number(r.value||0)),1);el.innerHTML=rows.map(r=>`<div class="bar-row"><div class="bar-label" title="${esc(r.label)}">${esc(r.label)}</div><div class="bar-track"><div class="bar-fill ${critical&&Number(r.critical)>0?'critical':''}" style="width:${Math.max(1,Number(r.value)*100/max)}%"></div></div><div class="bar-value">${fmt(r.value)}</div></div>`).join('')}

async function loadOverview(){const [o,c]=await Promise.all([api('/api/overview'),api('/api/charts')]);document.querySelector('#dbVersion').textContent=`Zabbix ${esc(o.current_dbversion||'7')}`;const s=o.status,ms=document.querySelector('#migrationStatus');ms.className=`migration-status ${s.level}`;ms.innerHTML=`<div class="status-dot"></div><div><strong>${esc(s.label)}</strong><span>${esc(s.detail)}</span></div>`;const sm=o.summary||{};const cards=[['Itens baseline',sm.baseline_healthy_items_analyzed,'saudáveis analisados'],['Regressões',sm.item_regressions,'itens'],['Templates impactados',o.templates_impacted,'templates base'],['Hosts impactados',sm.hosts_impacted,'hosts'],['LLD com perda',sm.lld_groups_with_loss,'grupos'],['Perda total LLD',sm.lld_total_loss,'grupos'],['Pendentes de deleção',o.pending_delete,'filhos LLD']];document.querySelector('#cards').innerHTML=cards.map(x=>`<div class="card"><div class="label">${esc(x[0])}</div><div class="value">${fmt(x[1])}</div><div class="hint">${esc(x[2])}</div></div>`).join('');barChart('#templateChart',c.templates,{critical:true});barChart('#categoryChart',c.categories);barChart('#hostChart',c.hosts,{critical:true});barChart('#lldChart',c.lld);barChart('#lldReasonChart',c.lld_reasons);document.querySelector('#errorList').innerHTML=c.errors.length?c.errors.map(e=>`<div class="error-row"><div class="error-count">${fmt(e.value)}</div><div class="error-text">${esc(e.label)}</div></div>`).join(''):'<div class="empty">Sem mensagens de erro registradas.</div>'}

async function loadRecommendations(){const d=await api('/api/recommendations');document.querySelector('#recBadge').textContent=d.count||'';document.querySelector('#recommendationsList').innerHTML=d.rows.length?d.rows.map(r=>`<article class="rec ${r.priority}"><div class="rec-head"><div class="rec-title"><span class="priority">${esc(r.priority)}</span><h3>${esc(r.title)}</h3></div><div class="rec-count">${fmt(r.count)}</div></div><p>${esc(r.why)}</p><div class="rec-action"><strong>Ação sugerida:</strong> ${esc(r.action)}</div>${r.evidence?.length?`<details><summary>Ver evidências (${r.evidence.length})</summary><div class="evidence">${r.evidence.map(e=>`<code>${esc(JSON.stringify(e,null,2))}</code>`).join('')}</div></details>`:''}</article>`).join(''):'<div class="empty">Nenhum ajuste recomendado pelos critérios atuais.</div>'}

function makeFilters(id,categories,withSeverity=true){const root=document.querySelector(id);const templateOptions=(state.filters?.templates||[]).map(x=>`<option value="${esc(x.template_hostid)}">#${fmt(x.rank)} · ${esc(x.template_name||x.template_host)}</option>`).join('');root.innerHTML=`<input data-f="q" placeholder="Buscar por host, item, key, ID ou erro"><select data-f="template"><option value="">Todos templates base</option>${templateOptions}</select><select data-f="severity"><option value="">Todas severidades</option>${withSeverity?['CRITICAL','HIGH','WARNING'].map(x=>`<option>${x}</option>`).join(''):''}</select><select data-f="category"><option value="">Todas categorias</option>${categories.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}</select>`;root.querySelectorAll('input,select').forEach(el=>{let t;el.oninput=()=>{clearTimeout(t);t=setTimeout(()=>{state.pages[state.view]=1;loadView(state.view)},250)}})}
function qsFor(view){const root=document.querySelector(view==='items'?'#itemFilters':view==='lld'?'#lldFilters':'#lldRuleFilters');const p=new URLSearchParams({page:state.pages[view],page_size:state.pageSize});root?.querySelectorAll('[data-f]').forEach(x=>{if(x.value)p.set(x.dataset.f,x.value)});return p}
function table(id,cols,rows){const t=document.querySelector(id);t.innerHTML=`<thead><tr>${cols.map(c=>`<th>${esc(c[0])}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${cols.map(c=>`<td class="${c[3]||''}">${c[2]?c[2](r[c[1]],r):esc(r[c[1]])}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${cols.length}" class="empty">Nenhum registro encontrado</td></tr>`}</tbody>`}
function pager(id,view,d){document.querySelector(id).innerHTML=`<button ${d.page<=1?'disabled':''} data-p="prev">Anterior</button><span>Página ${fmt(d.page)} de ${fmt(d.pages)} · ${fmt(d.total)} registros</span><button ${d.page>=d.pages?'disabled':''} data-p="next">Próxima</button>`;document.querySelectorAll(`${id} button`).forEach(b=>b.onclick=()=>{state.pages[view]+=b.dataset.p==='next'?1:-1;loadView(view)})}

async function loadItems(){if(!state.filters)state.filters=await api('/api/filters');if(!document.querySelector('#itemFilters').children.length)makeFilters('#itemFilters',state.filters.item_categories);const d=await api('/api/items?'+qsFor('items'));document.querySelector('#itemsMeta').textContent=`${fmt(d.total)} regressões encontradas`;table('#itemsTable',[['Sev.','severity',v=>sev(v)],['Template base','base_template_name',(v,r)=>tpl(v,r)],['Host','host_name',(v,r)=>esc(v||r.host)],['Item ID','itemid'],['Item','item_name'],['Key','key_',null,'category'],['Categoria','category',v=>`<span class="category">${esc(v)}</span>`],['Erro atual','current_error',v=>esc(v||''),'err'],['Master','master_itemid'],['Dependentes','dependent_affected_count',v=>fmt(v),'num'],['Campos alterados','changed_fields']],d.rows);pager('#itemsPager','items',d)}
async function loadLLD(){if(!state.filters)state.filters=await api('/api/filters');if(!document.querySelector('#lldFilters').children.length)makeFilters('#lldFilters',state.filters.lld_categories);const d=await api('/api/lld?'+qsFor('lld'));document.querySelector('#lldMeta').textContent=`${fmt(d.total)} grupos LLD`;table('#lldTable',[['Sev.','severity',v=>sev(v)],['Template base','base_template_name',(v,r)=>tpl(v,r)],['Host','host_name',(v,r)=>esc(v||r.host)],['Rule ID','ruleid'],['Discovery','rule_name'],['Baseline','baseline_count',v=>fmt(v),'num'],['Atual','current_present_count',v=>fmt(v),'num'],['Perdidos','lost_count',v=>fmt(v),'num'],['Perda','loss_pct',v=>pct(v),'num'],['Perda operacional','operational_loss_pct',v=>pct(v),'num'],['Not discovered','not_discovered_count',v=>fmt(v),'num'],['Pending delete','pending_delete_count',v=>fmt(v),'num'],['Desabilitados','disabled_count',v=>fmt(v),'num'],['Categoria','category',v=>`<span class="category">${esc(v)}</span>`]],d.rows);pager('#lldPager','lld',d)}
async function loadLLDRules(){if(!state.filters)state.filters=await api('/api/filters');if(!document.querySelector('#lldRuleFilters').children.length)makeFilters('#lldRuleFilters',state.filters.lld_rule_categories);const d=await api('/api/lld-rules?'+qsFor('lld-rules'));document.querySelector('#lldRuleMeta').textContent=`${fmt(d.total)} regras LLD com regressão`;table('#lldRuleTable',[['Sev.','severity',v=>sev(v)],['Template base','base_template_name',(v,r)=>tpl(v,r)],['Host','host_name',(v,r)=>esc(v||r.host)],['Rule ID','itemid'],['Regra','rule_name'],['Key','key_',null,'category'],['Categoria','category',v=>`<span class="category">${esc(v)}</span>`],['Erro atual','current_error',v=>esc(v||''),'err'],['Campos alterados','changed_fields']],d.rows);pager('#lldRulePager','lld-rules',d)}
async function loadRoots(){const d=await api('/api/roots');document.querySelector('#rootsMeta').textContent=`${fmt(d.total)} master items identificados`;table('#rootsTable',[['Sev.','severity',v=>sev(v)],['Template base','base_template_name',(v,r)=>tpl(v,r)],['Host','host_name',(v,r)=>esc(v||r.host)],['Item ID','itemid'],['Master item','item_name'],['Categoria','category',v=>`<span class="category">${esc(v)}</span>`],['Dependentes afetados','dependent_affected_count',v=>`<strong>${fmt(v)}</strong>`,'num'],['Erro atual','current_error',v=>esc(v||''),'err'],['Campos alterados','changed_fields']],d.rows)}
async function loadTemplates(){const root=document.querySelector('#templateFilters');if(!root.children.length){root.innerHTML='<input data-f="q" placeholder="Buscar template base">';root.querySelector('input').oninput=()=>{state.pages.templates=1;setTimeout(()=>loadTemplates(),150)}}const q=root.querySelector('input').value;const p=new URLSearchParams({page:state.pages.templates,page_size:state.pageSize,q,sort:'rank',dir:'asc'});const d=await api('/api/templates?'+p);document.querySelector('#templatesMeta').textContent=`${fmt(d.total)} templates base impactados · ordenados por prioridade`;table('#templatesTable',[['#','rank',v=>`<strong>${fmt(v)}</strong>`,'num'],['Template base','template_name',(v,r)=>`<strong>${esc(v||r.template_host)}</strong><div class="muted">${esc(r.template_host||'')}</div>`],['Impacto','impact_count',v=>`<strong>${fmt(v)}</strong>`,'num'],['Hosts','hosts_affected',v=>fmt(v),'num'],['Itens','item_regressions',v=>fmt(v),'num'],['Critical','critical_count',v=>sev(v>0?'CRITICAL':'OK')+' '+fmt(v),'num'],['High','high_count',v=>fmt(v),'num'],['Regras LLD','lld_rule_regressions',v=>fmt(v),'num'],['LLDs c/ perda','lld_groups_with_loss',v=>fmt(v),'num'],['Perda total','lld_total_loss',v=>fmt(v),'num'],['Filhos perdidos','lld_lost_children',v=>fmt(v),'num'],['Pending delete','lld_pending_delete',v=>fmt(v),'num'],['Dependentes','dependent_affected',v=>fmt(v),'num'],['Focar','template_hostid',(v,r)=>`<button class="focus-template" data-template="${esc(v)}" data-name="${esc(r.template_name)}">Ver itens</button>`]],d.rows);document.querySelectorAll('.focus-template').forEach(b=>b.onclick=()=>focusTemplate(b.dataset.template,b.dataset.name));pager('#templatesPager','templates',d)}
function focusTemplate(id,name){showView('items');setTimeout(()=>{const sel=document.querySelector('#itemFilters [data-f="template"]');if(sel){sel.value=id;state.pages.items=1;loadItems();toast(`Filtro aplicado: ${name}`)}},80)}

async function loadHosts(){const root=document.querySelector('#hostFilters');if(!root.children.length){root.innerHTML='<input data-f="q" placeholder="Buscar host">';root.querySelector('input').oninput=()=>{state.pages.hosts=1;setTimeout(()=>loadHosts(),150)}}const q=root.querySelector('input').value;const p=new URLSearchParams({page:state.pages.hosts,page_size:state.pageSize,q});const d=await api('/api/hosts?'+p);document.querySelector('#hostsMeta').textContent=`${fmt(d.total)} hosts impactados`;table('#hostsTable',[['Host','host_name',(v,r)=>esc(v||r.host)],['Total','anomaly_count',v=>`<strong>${fmt(v)}</strong>`,'num'],['Critical','critical_count',v=>fmt(v),'num'],['High','high_count',v=>fmt(v),'num'],['Warning','warning_count',v=>fmt(v),'num'],['Categorias','category_count',v=>fmt(v),'num'],['Dependentes afetados','dependent_affected_count',v=>fmt(v),'num']],d.rows);pager('#hostsPager','hosts',d)}

async function loadView(view,refresh=false){try{if(refresh)state.filters=null;({overview:loadOverview,recommendations:loadRecommendations,items:loadItems,lld:loadLLD,'lld-rules':loadLLDRules,roots:loadRoots,templates:loadTemplates,hosts:loadHosts}[view])();if(view!=='recommendations')loadRecommendations().catch(()=>{});if(refresh)toast('Dados atualizados')}catch(e){toast(e.message)}}
loadOverview().catch(e=>toast(e.message));loadRecommendations().catch(()=>{});
